name: API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install Newman and Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
        
    - name: Run API Tests
      run: |
        newman run serverest_collection.json \
          --environment serverest_dev_environment_global.json \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export newman/report.html
          
    - name: Archive Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-report
        path: newman/report.html
        retention-days: 30
        
    - name: Check Test Status
      if: failure()
      run: |
        echo "::error::API Tests failed! Check the test report for details."
        exit 1
